# Generated by Django 6.0.7 on 2026-07-27 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_id', models.IntegerField()),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Pending Rep Verification', 'Pending Rep Verification'), ('Student Rep Verified', 'Student Rep Verified'), ('Correction Requested', 'Correction Requested'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Evaluated', 'Evaluated'), ('Locked', 'Locked'), ('Correction', 'Correction')], default='Draft', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('proof', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluator_verified', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
