# Generated by Django 6.0.7 on 2026-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verified_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('evaluation', 'Evaluation Team'), ('iqac', 'IQAC'), ('admin', 'Admin')], max_length=20),
        ),
    ]
