# Generated by Django 6.0.7 on 2026-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_submission_verified_by_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('evaluation', 'Evaluation Team'), ('admin', 'Admin')], max_length=20),
        ),
    ]
