# Generated by Django 6.0.7 on 2026-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_criteriacategory_systemsetting_usergroupmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriacategory',
            name='evaluators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Pending Rep Verification', 'Pending Rep Verification'), ('Student Rep Verified', 'Student Rep Verified'), ('Teacher Verified', 'Teacher Verified'), ('Correction Requested', 'Correction Requested'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Evaluated', 'Evaluated'), ('Locked', 'Locked'), ('Correction', 'Correction')], default='Draft', max_length=50),
        ),
    ]
