# Generated by Django 6.0.7 on 2026-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_criteriacategory_evaluators_alter_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('rankLabel', models.CharField(max_length=50)),
                ('teamName', models.CharField(max_length=100)),
                ('eventName', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='champions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'rank'],
            },
        ),
    ]
