# Generated by Django 6.0.7 on 2026-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='eventName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
