# Generated by Django 5.1.15 on 2026-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_champion_eventname_alter_champion_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
