# Generated by Django 6.0.7 on 2026-09-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_submission_end_date_submission_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(default='standard', max_length=50)),
                ('maximum_marks', models.FloatField(blank=True, null=True)),
                ('min_count', models.IntegerField(blank=True, null=True)),
                ('max_count', models.IntegerField(blank=True, null=True)),
                ('is_negative', models.BooleanField(default=False)),
                ('multiplier', models.FloatField(default=1.0)),
                ('extra_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='users.criteriaitem')),
            ],
        ),
    ]
