# Generated by Django 6.0.7 on 2026-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_criteriarule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaudittrail',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowaudittrail',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workflowaudittrail',
            name='record_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workflowaudittrail',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowaudittrail',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
