# Generated by Django 6.0.7 on 2026-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_workflowaudittrail_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='certificate_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='proof_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
