# Generated by Django 5.1.15 on 2026-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_submission_certificate_id_submission_proof_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='category',
            field=models.CharField(default='UG', max_length=20),
        ),
    ]
