# Generated by Django 6.0.7 on 2026-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_champion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='negative_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='class',
            name='num_students',
            field=models.IntegerField(default=0),
        ),
    ]
