# Generated by Django 6.0.7 on 2026-09-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_class_negative_points_class_num_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='batch_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='class',
            name='year_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email_prefix',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('UG', 'Under-Graduate'), ('PG', 'Post-Graduate'), ('Professional', 'Professional'), ('Other', 'Other')], default='UG', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('abbreviation', models.CharField(max_length=20)),
                ('email_code', models.CharField(max_length=10)),
                ('is_multi_batch', models.BooleanField(default=False)),
                ('duration_years', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.department')),
            ],
            options={
                'unique_together': {('department', 'email_code')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='users.course'),
        ),
    ]
