# Generated by Django 6.0.7 on 2026-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_clean_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgradebreakdown',
            name='other_pass_count',
            field=models.IntegerField(default=0),
        ),
    ]
