# Generated by Django 6.0.7 on 2026-09-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_academicgradebreakdown_other_pass_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bug_type', models.CharField(choices=[('UI', 'UI / Layout'), ('Function', 'Functionality / Logic'), ('Performance', 'Performance / Speed'), ('Other', 'Other')], default='UI', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('browser_device', models.CharField(blank=True, default='', max_length=255)),
                ('page_url', models.CharField(blank=True, default='', max_length=255)),
                ('role_category', models.CharField(default='Student', max_length=100)),
                ('reporter_name', models.CharField(blank=True, default='', max_length=150)),
                ('reporter_email', models.CharField(blank=True, default='', max_length=150)),
                ('whatsapp_numbers', models.CharField(blank=True, default='', max_length=255)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bug_reports/')),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
