# Generated by Django 6.0.7 on 2026-09-08 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['academic_year', '-version'],
                'unique_together': {('academic_year', 'version')},
            },
        ),
        migrations.AddField(
            model_name='criteriaitem',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='users.criteriaversion'),
        ),
        migrations.AddField(
            model_name='submission',
            name='criteria_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='users.criteriaversion'),
        ),
    ]
