# Generated by Django 6.0.7 on 2026-09-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0020_criteriaversion_criteriaitem_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='criteriaversion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classindexresult',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.academicyear'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'status'], name='idx_sub_user_status'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['academic_year', 'status'], name='idx_sub_year_status'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['criteria_id', 'status'], name='idx_sub_criteria_status'),
        ),
        migrations.AddIndex(
            model_name='workflowaudittrail',
            index=models.Index(fields=['submission', 'created_at'], name='idx_audit_sub_created'),
        ),
        migrations.AddConstraint(
            model_name='academicgradebreakdown',
            constraint=models.CheckConstraint(condition=models.Q(('s_grade_count__gte', 0), ('a_plus_grade_count__gte', 0), ('a_grade_count__gte', 0), ('other_pass_count__gte', 0), ('failed_count__gte', 0)), name='check_grade_counts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='academicgradebreakdown',
            constraint=models.CheckConstraint(condition=models.Q(('total_students__gte', 0)), name='check_grade_total_students_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='academicgradebreakdown',
            constraint=models.CheckConstraint(condition=models.Q(('class_pass_percentage__gte', 0.0), ('class_pass_percentage__lte', 100.0)), name='check_grade_pass_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('year__regex', '^\\d{4}-\\d{4}$')), name='check_academic_year_format'),
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(condition=models.Q(('bug_type__in', ['UI', 'Function', 'Performance', 'Other'])), name='check_bug_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['Low', 'Medium', 'High'])), name='check_bug_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Open', 'In Progress', 'Resolved'])), name='check_bug_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='check_champion_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.UniqueConstraint(fields=('year', 'category', 'rank', 'teamName'), name='unique_year_category_rank_team'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), models.Q(('section', ''), _negated=True)), fields=('course', 'year_number', 'section'), name='unique_course_year_section'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('num_students__gte', 0)), name='check_class_num_students_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('negative_points__gte', 0.0)), name='check_class_negative_points_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('year_number__isnull', True), models.Q(('year_number__gte', 1), ('year_number__lte', 6)), _connector='OR'), name='check_class_year_number_range'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('batch_start_year__isnull', True), models.Q(('batch_start_year__gte', 1990), ('batch_start_year__lte', 2100)), _connector='OR'), name='check_class_batch_start_year_range'),
        ),
        migrations.AddConstraint(
            model_name='classindexresult',
            constraint=models.UniqueConstraint(fields=('class_name', 'academic_year'), name='unique_class_academic_year_result'),
        ),
        migrations.AddConstraint(
            model_name='classindexresult',
            constraint=models.CheckConstraint(condition=models.Q(('rank__isnull', True), ('rank__gte', 1), _connector='OR'), name='check_class_index_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='classindexresult',
            constraint=models.CheckConstraint(condition=models.Q(('final_index__gte', 0.0)), name='check_class_index_final_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='classindexresult',
            constraint=models.CheckConstraint(condition=models.Q(('academic_score__gte', 0.0), ('co_curricular_score__gte', 0.0), ('extra_curricular_score__gte', 0.0)), name='check_class_index_scores_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'email_code'), name='unique_department_email_code'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('duration_years__gte', 1), ('duration_years__lte', 6)), name='check_course_duration_years_range'),
        ),
        migrations.AddConstraint(
            model_name='criteriaitem',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['count', 'fixed', 'range', 'negative', 'academic_grades', 'date'])), name='check_criteria_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='criteriarule',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gte', 0.0)), name='check_criteria_rule_multiplier_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='criteriarule',
            constraint=models.CheckConstraint(condition=models.Q(('min_count__isnull', True), ('min_count__gte', 0), _connector='OR'), name='check_criteria_rule_min_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='criteriarule',
            constraint=models.CheckConstraint(condition=models.Q(('max_count__isnull', True), ('max_count__gte', 0), _connector='OR'), name='check_criteria_rule_max_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='criteriaversion',
            constraint=models.UniqueConstraint(fields=('academic_year', 'version'), name='unique_academic_year_version'),
        ),
        migrations.AddConstraint(
            model_name='criteriaversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='check_criteria_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['UG', 'PG', 'Professional', 'Other'])), name='check_department_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Approved', 'Pending', 'Pending Rep Verification', 'Student Rep Verified', 'Teacher Verified', 'Correction Requested', 'Rejected', 'Draft', 'Submitted', 'Verified', 'Evaluated', 'Locked', 'Correction'])), name='check_submission_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('certificate_id__isnull', False), models.Q(('certificate_id', ''), _negated=True), models.Q(('status', 'Rejected'), _negated=True)), fields=('user', 'certificate_id'), name='unique_active_user_certificate'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('proof_hash__isnull', False), models.Q(('proof_hash', ''), _negated=True), models.Q(('status', 'Rejected'), _negated=True)), fields=('user', 'proof_hash'), name='unique_active_user_proof_hash'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['student', 'faculty', 'evaluation', 'iqac', 'admin'])), name='check_user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('roll_number__isnull', True), ('roll_number__gte', 0), _connector='OR'), name='check_user_roll_number_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('batch_year__isnull', True), models.Q(('batch_year__gte', 1990), ('batch_year__lte', 2100)), _connector='OR'), name='check_user_batch_year_range'),
        ),
        migrations.AddConstraint(
            model_name='workflowaudittrail',
            constraint=models.CheckConstraint(condition=models.Q(('stage__gte', 1), ('stage__lte', 7)), name='check_audit_stage_range'),
        ),
    ]
