# Generated by Django 6.0.7 on 2026-09-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_database_integrity_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='classindexresult',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classindexresult',
            name='scoring_version',
            field=models.CharField(default='v1.0-authoritative', max_length=50),
        ),
        migrations.AddField(
            model_name='classindexresult',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
