# Generated by Django 6.0.7 on 2026-09-09 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_classindexresult_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('object_type', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id', 'created_at'], name='idx_audit_obj_created'), models.Index(fields=['action', 'created_at'], name='idx_audit_act_created')],
            },
        ),
    ]
