# Generated by Django 6.0.7 on 2026-09-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_system_audit_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classindexresult',
            index=models.Index(fields=['academic_year', 'is_locked'], name='idx_cir_year_locked'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'academic_year'], name='idx_sub_status_year'),
        ),
    ]
