# Generated by Django 6.1.1 on 2026-09-10 17:53

from django.db import migrations, models


def cleanup_iqac_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(models.Q(role='iqac') | models.Q(email__icontains='iqac')).delete()
    # Fallback to ensure no invalid roles remain
    User.objects.exclude(role__in=['student', 'faculty', 'evaluation', 'admin']).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0024_classindexresult_idx_cir_year_locked_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='check_user_role_valid',
        ),
        migrations.RunPython(cleanup_iqac_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('evaluation', 'Evaluation Team'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['student', 'faculty', 'evaluation', 'admin'])), name='check_user_role_valid'),
        ),
    ]
