# Generated by Django 6.1.1 on 2026-09-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_classindexresult_idx_cir_year_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaitem',
            name='access_level',
            field=models.CharField(default='all_students', max_length=20),
        ),
    ]
