# Generated by Django 6.1.1 on 2026-09-11 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0026_usergroupmember_evaluatorcategoryassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher_class_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_level', models.CharField(choices=[('DQC', 'DQC'), ('CLASS_TEACHER', 'Class Teacher'), ('EVALUATOR', 'Evaluator')], max_length=50)),
                ('verifier_id', models.IntegerField(blank=True, null=True)),
                ('verifier_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('VERIFY_AND_FORWARD', 'Verify and Forward'), ('SEND_BACK', 'Send Back'), ('REJECT', 'Reject')], max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='evaluatorcategoryassignment',
            name='unique_member_category_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='check_submission_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='check_user_role_valid',
        ),
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='criteriacategory',
            name='is_manual_eval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criteriaitem',
            name='access_level',
            field=models.CharField(default='all_students', max_length=50),
        ),
        migrations.AddField(
            model_name='criteriaitem',
            name='is_manual_eval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluatorcategoryassignment',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_category_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='calculated_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='users.criteriacategory'),
        ),
        migrations.AddField(
            model_name='submission',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='users.class'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_manual_eval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='proof_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='subcategory_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluatorcategoryassignment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='users.usergroupmember'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='proof',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Pending Rep Verification', 'Pending Rep Verification'), ('Student Rep Verified', 'Student Rep Verified'), ('Teacher Verified', 'Teacher Verified'), ('Correction Requested', 'Correction Requested'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Evaluated', 'Evaluated'), ('Locked', 'Locked'), ('Correction', 'Correction'), ('DQC_PENDING', 'DQC Pending'), ('TEACHER_PENDING', 'Teacher Pending'), ('EVALUATOR_PENDING', 'Evaluator Pending'), ('APPROVED', 'Approved (Canonical)'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected (Canonical)')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('evaluation', 'Evaluation Team'), ('admin', 'Admin'), ('STUDENT', 'Student (Uppercase)'), ('STAFF', 'Staff (Uppercase)'), ('ADMIN', 'Admin (Uppercase)')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='evaluatorcategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('member', 'category'), name='unique_member_category_assignment'),
        ),
        migrations.AddConstraint(
            model_name='evaluatorcategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator__isnull', False)), fields=('evaluator', 'category'), name='unique_evaluator_category_assignment'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Approved', 'Pending', 'Pending Rep Verification', 'Student Rep Verified', 'Teacher Verified', 'Correction Requested', 'Rejected', 'Draft', 'Submitted', 'Verified', 'Evaluated', 'Locked', 'Correction', 'DQC_PENDING', 'TEACHER_PENDING', 'EVALUATOR_PENDING', 'APPROVED', 'SENT_BACK', 'REJECTED'])), name='check_submission_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['student', 'faculty', 'evaluation', 'admin', 'STUDENT', 'STAFF', 'ADMIN'])), name='check_user_role_valid'),
        ),
        migrations.AlterModelTable(
            name='evaluatorcategoryassignment',
            table='evaluator_category_assignments',
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='users.class'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='users.submission'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'class_obj'), name='unique_teacher_class_assignment'),
        ),
    ]
