# Generated by Django 6.1.1 on 2026-09-11 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_teacherclassassignment_verificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.RemoveConstraint(
            model_name='evaluatorcategoryassignment',
            name='unique_evaluator_category_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='teacherclassassignment',
            name='unique_teacher_class_assignment',
        ),
        migrations.AddField(
            model_name='evaluatorcategoryassignment',
            name='academic_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='evaluatorcategoryassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluator_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluatorcategoryassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='academic_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teacher_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evaluatorcategoryassignment',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to='users.criteriacategory'),
        ),
        migrations.AlterField(
            model_name='evaluatorcategoryassignment',
            name='evaluator',
            field=models.ForeignKey(blank=True, db_column='evaluator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_category_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='calculated_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherclassassignment',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='users.class'),
        ),
        migrations.AlterField(
            model_name='teacherclassassignment',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='action',
            field=models.CharField(choices=[('VERIFY_AND_FORWARD', 'Verify and Forward'), ('SEND_BACK', 'Send Back'), ('REJECT', 'Reject'), ('APPROVE_AND_CREDIT', 'Approve and Credit')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='evaluatorcategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator__isnull', False)), fields=('evaluator', 'category', 'academic_year'), name='unique_evaluator_category'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_year'), name='unique_single_teacher_per_year'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('class_obj',), name='unique_single_class_teacher'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='users.department'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
