# Generated by Django 6.1.1 on 2026-09-11 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_staffprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationlog',
            options={'ordering': ['action_timestamp', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='verificationlog',
            name='verifier_id',
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='action_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='verifier',
            field=models.ForeignKey(blank=True, db_column='verifier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
