from django.conf import settings
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    GoogleLoginView,
    DevBypassLoginView,
    LogoutView,
    UserProfileView,
    ClassListView,
    ClassDetailView,
    ClassIndexView,
    SubmissionListView,
    SubmissionDetailView,
    AcademicYearListView,
    DepartmentListView,
    DepartmentDetailView,
    CourseListView,
    CourseDetailView,
    UserManagementView,
    SystemSettingView,
    UserGroupListView,
    UserGroupDetailView,
    CriteriaCategoryListView,
    CriteriaCategoryDetailView,
    CriteriaItemListView,
    CriteriaItemDetailView,
    ChampionListView,
    ChampionDetailView
)

urlpatterns = [
    path('auth/google/', GoogleLoginView.as_view(), name='google-login'),
    path('auth/bypass/', DevBypassLoginView.as_view(), name='dev-bypass-login'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/profile/', UserProfileView.as_view(), name='user-profile'),
    path('auth/classes/', ClassListView.as_view(), name='class-list'),
    path('auth/classes/<int:pk>/', ClassDetailView.as_view(), name='class-detail'),
    path('class-index/', ClassIndexView.as_view(), name='class-index'),
    path('academic-years/', AcademicYearListView.as_view(), name='academic-years'),
    path('departments/', DepartmentListView.as_view(), name='departments'),
    path('departments/<int:pk>/', DepartmentDetailView.as_view(), name='department-detail'),
    path('courses/', CourseListView.as_view(), name='courses'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('users/', UserManagementView.as_view(), name='user-management'),
    path('submissions/', SubmissionListView.as_view(), name='submission-list'),
    path('submissions/<int:pk>/', SubmissionDetailView.as_view(), name='submission-detail'),
    path('settings/', SystemSettingView.as_view(), name='system-settings'),
    path('user-groups/', UserGroupListView.as_view(), name='user-groups'),
    path('user-groups/<str:pk>/', UserGroupDetailView.as_view(), name='user-group-detail'),
    path('criteria-categories/', CriteriaCategoryListView.as_view(), name='criteria-categories'),
    path('criteria-categories/<str:pk>/', CriteriaCategoryDetailView.as_view(), name='criteria-category-detail'),
    path('criteria-items/', CriteriaItemListView.as_view(), name='criteria-items'),
    path('criteria-items/<int:pk>/', CriteriaItemDetailView.as_view(), name='criteria-item-detail'),
    path('champions/', ChampionListView.as_view(), name='champions-list'),
    path('champions/<int:pk>/', ChampionDetailView.as_view(), name='champions-detail'),
]
