from django.urls import path
from .views import (
    GoogleLoginView,
    CustomTokenRefreshView,
    LogoutView,
    UserProfileView,
    SwitchRoleView,
    ClassListView,
    ClassDetailView,
    ClassIndexView,
    SubmissionListView,
    SubmissionDetailView,
    SubmissionEvidenceView,
    AcademicYearListView,
    DepartmentListView,
    DepartmentDetailView,
    CourseListView,
    CourseDetailView,
    UserManagementView,
    SystemSettingView,
    UserGroupListView,
    UserGroupDetailView,
    UserGroupMemberActionView,
    CriteriaVersionListView,
    CriteriaVersionDetailView,
    CriteriaCategoryListView,
    CriteriaCategoryDetailView,
    CriteriaItemListView,
    CriteriaItemDetailView,
    SubCategoryListView,
    SubCategoryDetailView,
    ChampionListView,
    ChampionDetailView,
    BugReportView,
    SystemAuditLogView,
    SubmissionAuditTrailView,
    HealthCheckView,
    DQCVerificationView,
    TeacherVerificationView,
    EvaluatorVerificationView,
)

urlpatterns = [
    path('health/', HealthCheckView.as_view(), name='health-check'),
    path('verification/dqc/', DQCVerificationView.as_view(), name='verification-dqc'),
    path('verification/round1/', DQCVerificationView.as_view(), name='verification-round1'),
    path('verification/teacher/', TeacherVerificationView.as_view(), name='verification-teacher'),
    path('verification/round2/', TeacherVerificationView.as_view(), name='verification-round2'),
    path('verification/evaluator/', EvaluatorVerificationView.as_view(), name='verification-evaluator'),
    path('verification/round3/', EvaluatorVerificationView.as_view(), name='verification-round3'),
    path('auth/google/', GoogleLoginView.as_view(), name='google-login'),
    path('auth/token/refresh/', CustomTokenRefreshView.as_view(), name='token-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/profile/', UserProfileView.as_view(), name='user-profile'),
    path('auth/switch-role/', SwitchRoleView.as_view(), name='switch-role'),
    path('auth/classes/', ClassListView.as_view(), name='class-list'),
    path('auth/classes/<int:pk>/', ClassDetailView.as_view(), name='class-detail'),
    path('class-index/', ClassIndexView.as_view(), name='class-index'),
    path('academic-years/', AcademicYearListView.as_view(), name='academic-years'),
    path('departments/', DepartmentListView.as_view(), name='departments'),
    path('departments/<int:pk>/', DepartmentDetailView.as_view(), name='department-detail'),
    path('courses/', CourseListView.as_view(), name='courses'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('users/', UserManagementView.as_view(), name='user-management'),
    path('submissions/', SubmissionListView.as_view(), name='submission-list'),
    path('submissions/<int:pk>/', SubmissionDetailView.as_view(), name='submission-detail'),
    path('submissions/<int:pk>/audit/', SubmissionAuditTrailView.as_view(), name='submission-audit'),
    path('submissions/<int:pk>/evidence/', SubmissionEvidenceView.as_view(), name='submission-evidence'),
    path('audit-logs/', SystemAuditLogView.as_view(), name='system-audit-logs'),
    path('settings/', SystemSettingView.as_view(), name='system-settings'),
    path('user-groups/', UserGroupListView.as_view(), name='user-groups'),
    path('user-groups/<str:pk>/', UserGroupDetailView.as_view(), name='user-group-detail'),
    path('user-groups/<str:pk>/add_member/', UserGroupMemberActionView.as_view(), name='user-group-add-member'),
    path('user-groups/<str:pk>/remove_member/', UserGroupMemberActionView.as_view(), name='user-group-remove-member'),
    path('criteria-versions/', CriteriaVersionListView.as_view(), name='criteria-versions'),
    path('criteria-versions/<int:pk>/', CriteriaVersionDetailView.as_view(), name='criteria-version-detail'),
    path('criteria-categories/', CriteriaCategoryListView.as_view(), name='criteria-categories'),
    path('criteria-categories/<str:pk>/', CriteriaCategoryDetailView.as_view(), name='criteria-category-detail'),
    path('criteria-items/', CriteriaItemListView.as_view(), name='criteria-items'),
    path('criteria-items/<int:pk>/', CriteriaItemDetailView.as_view(), name='criteria-item-detail'),
    path('subcategories/', SubCategoryListView.as_view(), name='subcategory-list'),
    path('subcategories/<int:pk>/', SubCategoryDetailView.as_view(), name='subcategory-detail'),
    path('champions/', ChampionListView.as_view(), name='champions-list'),
    path('champions/<int:pk>/', ChampionDetailView.as_view(), name='champions-detail'),
    path('bug-reports/', BugReportView.as_view(), name='bug-reports'),
]

